import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import '../src/renderer/styles/app.css';
import '../src/renderer/styles/inspector-refresh.css';
import { LabviewProjectPanel } from '../src/renderer/components/LabviewProjectSources';
import { UI } from '../src/renderer/components/ui';

globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const results = [], root = createRoot(document.getElementById('root'));
let props, calls;
const assert = (value, message) => { if (!value) throw new Error(message); };
async function native(request) { await new Promise((resolve) => { window.__pushUiRequest = request; window.__finishPushUiRequest = () => { window.__pushUiRequest = null; resolve(); }; }); }
const button = (label) => [...document.querySelectorAll('button')].find((button) => button.textContent === label || button.getAttribute('aria-label') === label);
async function pointer(label) { const el = button(label); assert(el, 'Missing '+label); el.scrollIntoView({ block: 'nearest' }); const rect = el.getBoundingClientRect(); await act(async () => native({ pointer: { x: Math.round(rect.x + rect.width/2), y: Math.round(rect.y + rect.height/2) } })); }
const catalog = { projectName: 'Competition robot 2468 — autonomous command project', commands: [{ id: 'shoot', label: 'Shoot game piece' }], warnings: ['Fixture discovery warning: one reference could not be resolved.'], labviewDiscovery: { projectFile: 'Robot/Competition robot and command library.lvproj', viCount: 123, targets: [{ name: 'roboRIO' }], items: Array.from({ length: 43 }, (_, i) => ({ name: 'Command ' + i + '.vi', file: 'Commands/Autonomous/Command ' + i + '.vi', target: 'roboRIO', projectPath: 'Commands/' + i, status: 'present' })), inspection: { commandCount: 1, unsupported: [] } } };
function Harness() { return <div style={{display:'flex',height:'100vh',background:'var(--bg-1)'}}><main style={{flex:1,padding:32,color:'var(--txt-3)'}}><h2>Command editor verification</h2><p>Isolated LabVIEW project fixture</p></main><aside className="ctxinsp inspector-refresh"><div className="ctxinsp-hd"><span className="ctxinsp-t">Intake command</span></div><div className="ctxinsp-body"><LabviewProjectPanel robotProject={props}/><label className="fieldlabel">Name</label><input className="textinput" defaultValue="Start intake"/><UI.ChoiceBrowser id="fixture-command" label="Command" value="shoot" items={[{ value:'shoot',label:'Shoot game piece',meta:'Target speed, Duration' }]} onChange={()=>{}}/><div className="cgroup-h">Parameters</div><label className="fieldlabel">Target speed</label><input className="textinput" defaultValue="2400"/></div></aside></div>; }
async function render() { await act(async () => root.render(<Harness/>)); }
async function mount(platform='win32', linked=true) { await act(async()=>root.render(null)); window.bordeauxAPI={platform}; calls=[]; props={ catalog:linked?structuredClone(catalog):null, bookmarkId:'current', operation:null, status:'ready', recentProjects:[{id:'other',projectName:'Practice robot with a very long descriptive project name',folderName:'C:/Robots/Practice Robot'}], link:()=>calls.push('link'), refresh:()=>calls.push('refresh'), openRecent:(id)=>calls.push(id)}; await render(); }
async function test(name,fn) {try {await fn(); results.push({name,ok:true});}catch(error){results.push({name,ok:false,error:error.message});}}
await test('Unlinked project selection is visible without a disclosure',async()=>{await mount('win32',false); assert(!document.querySelector('details'),'No disclosure'); await pointer('Choose LabVIEW project'); assert(calls[0]==='link','Selection called'); await native({capture:'unlinked'});});
await test('Windows ready project exposes change and full sync',async()=>{await mount(); await pointer('Sync commands'); assert(calls[0]==='refresh','Sync refreshes'); await pointer('Change project'); assert(calls[1]==='link','Change opens project'); assert(document.querySelector('.labview-project-name').textContent===catalog.projectName,'Cancel retains project'); await native({capture:'windows-ready'});});
await test('Pending synchronization disables competing actions',async()=>{props.operation='scan';await render();assert(button('Change project').disabled&&button('Sync commands').disabled,'Disabled actions');assert(document.querySelector('[aria-busy="true"]'),'Busy status');await native({capture:'syncing'});});
await test('Failure stays visible with a usable sync retry',async()=>{props.operation=null;props.error='LabVIEW is not running. Open the robot project in LabVIEW, then sync commands.';await render();assert(document.querySelector('[role="alert"]'),'Visible error');assert(!button('Sync commands').disabled,'Retry enabled');await native({capture:'sync-error'});});
await test('Recent project choice uses explicit rows and retains context on cancel',async()=>{await mount();await pointer('Recent projects');assert(document.querySelector('.labview-recent-projects'),'Recent rows');await pointer(props.recentProjects[0].projectName+'C:/Robots/Practice Robot');assert(calls[0]==='other','Recent chosen');await native({capture:'recent-projects'});await pointer('Hide recent projects');assert(!document.querySelector('.labview-recent-projects'),'Hide');});
await test('Project sources support pointer, keyboard, search and warnings without carets',async()=>{await mount();await pointer('View sources (123 VIs)');assert(document.querySelectorAll('.labview-source-row').length===40,'Pagination');assert(document.querySelector('.labview-source-warnings'),'Warnings');await native({capture:'project-sources'});await pointer('Hide sources');await act(async()=>native({key:'Enter'}));assert(document.querySelector('.labview-source-list'),'Enter toggles focused source action');await act(async()=>native({key:'Tab'}));assert(document.activeElement.type==='search','Tab reaches source search');await act(async()=>{const el=document.activeElement;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'unmatched');el.dispatchEvent(new Event('input',{bubbles:true}));});assert(document.querySelector('.labview-source-list').textContent.includes('No sources match'),'Search empty');await act(async()=>native({key:'Escape'}));assert(document.activeElement.value==='','Escape clears search');});
await test('Mac retains saved inputs and allows source resync',async()=>{await mount('darwin');assert(document.querySelector('.labview-project-help').textContent.includes('Windows'),'Platform guidance');assert(!button('Sync commands').disabled,'Mac refresh allowed');await pointer('Sync commands');assert(calls[0]==='refresh','Mac refresh');await native({capture:'mac-ready'});});
await act(async()=>root.render(<pre id="verification-report">{JSON.stringify(results,null,2)}</pre>));
